# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install pandoc
        run: |
          wget -O pandoc.deb https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb
          sudo dpkg -i ./pandoc.deb
          rm pandoc.deb
      - name: Build
        run: |
          python3 ./publish.py posts/*
      - name: Publish
        run: |
          cp -r site/* .
          git config --global user.name "Github Actions"
          git config --global user.email actions@github.com
          git checkout --orphan gh-pages
          git add -A
          git commit -am "Publish website"
          git push -f origin gh-pages
